### ISSUE TITLE
2.2.6 create dump file failed

### ISSUE THREAD

**Issue by liu-yfeng** [6opuc/lldb-netcore#1]
2.2.6 create dump file failed

**Comment by 6opuc** [comment]
Sorry for delay.
I've just rebuild docker image with netcore 2.2.6 base images and it works as expected.
I've been using this test: https://github.com/6opuc/lldb-netcore-use-cases/blob/master/hang_cpu_idle.md

New images were pushed to docker hub.

Please, let me know if you have any trouble with it.

**Comment by liu-yfeng** [comment]
> Sorry for delay.
> I've just rebuild docker image with netcore 2.2.6 base images and it works as expected.
> I've been using this test: https://github.com/6opuc/lldb-netcore-use-cases/blob/master/hang_cpu_idle.md
> 
> New images were pushed to docker hub.
> 
> Please, let me know if you have any trouble with it.

Thank you very much
